---
- name: Configure PCs
  hosts: pcs
  become: yes
  tasks:
    - name: Install DHCP client (Alpine)
      apk:
        name: dhcpcd
        state: present
      when: ansible_os_family == "Alpine"

    - name: Start DHCP client
      command: dhcpcd eth0
      async: 30
      poll: 0