---
- name: Configure Servers
  hosts: servers
  become: yes
  tasks:
    - name: Configure network persistently
      nmcli:
        conn_name: "eth0"
        ifname: "eth0"
        type: "ethernet"
        ip4: "{{ ip_address }}/24"
        gw4: "{{ gateway }}"
        state: present

    - name: Install Apache
      package:
        name: apache2
        state: present
      tags: install_apache

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes